# Generated by Django 4.0.10 on 2023-03-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog title of the blog', max_length=255, null=True, verbose_name='Blog title')),
                ('body', models.TextField(help_text='Blog title of the blog', null=True, verbose_name='Blog title')),
            ],
        ),
    ]
