# Generated by Django 4.0.10 on 2023-03-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytestApis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='this stroes the actual date and time for the blog', null=True, verbose_name='Created date'),
        ),
        migrations.AddField(
            model_name='news',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='this stroes the updated date and time when the blog was updated last', null=True, verbose_name='Created date'),
        ),
    ]
