# Generated by Django 4.0.10 on 2023-03-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_pin', models.CharField(help_text='This field store the OTP pin for verification', max_length=6, null=True, verbose_name='OTP Pin')),
                ('email', models.EmailField(help_text='this is the user email that will be used during the verification', max_length=254, null=True, verbose_name='Email')),
            ],
        ),
    ]
