# Generated by Django 4.0.10 on 2023-03-28 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP_Notifications', '0003_alter_otp_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='pin_duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 15, 32, 47, 98903), help_text='this holds the duration for the pin sent to the user email', null=True, verbose_name='OTP pin duration'),
        ),
    ]
