# Generated by Django 4.0.10 on 2023-03-28 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OTP_Notifications', '0004_otp_pin_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='pin_duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 15, 33, 18, 559250, tzinfo=utc), help_text='this holds the duration for the pin sent to the user email', null=True, verbose_name='OTP pin duration'),
        ),
    ]
