# Generated by Django 4.0.10 on 2023-03-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP_Notifications', '0005_alter_otp_pin_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='pin_duration',
            field=models.DateTimeField(help_text='this holds the duration for the pin sent to the user email', null=True, verbose_name='OTP pin duration'),
        ),
    ]
